[phases.setup]
nixPkgs = ["jdk17", "maven"]

[build]
buildCommand = "cd backend && mvn clean package -DskipTests"

[start]
startCommand = "cd backend && java -jar target/stackoverflow-0.0.1-SNAPSHOT.jar"
