[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.build]
cmd = "cd backend && mvn clean package -DskipTests"

[phases.start]
cmd = "cd backend && java -jar target/stackoverflow-0.0.1-SNAPSHOT.jar"
